version: '3.5'

x-defaults: &defaults
  logging:
    options:
      max-file: "4"
      max-size: "50m"

services:
  dyamodb-example:
    build:
      context: ./examples/dynamodb/
    volumes:
      - ./examples/dynamodb/src:/src
    environment:
      AWS_DEFAULT_REGION: "ap-southeast-2"